### ISSUE TITLE
Consider bumping minimum required `node` version.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [malept/sumchecker#3]
If you bump to at least `node@0.12.0`, you can drop the dependency on `es6-promise`.  Also, `node@0.10.0` isn't supported anymore, so there's that.

**Comment by wtgtybhertgeghgtwtg** [comment]
Actually, if you went a bit further and bumped to at least `node@4.0.0`, you could drop `babel` and the transpilation step, too.

**Comment by malept** [comment]
I am planning on dropping Node < 4 at the start of 2017.
