### ISSUE TITLE
Error validating checksums on node.js 8

### ISSUE THREAD

**Issue by antelle** [malept/sumchecker#7]
Hello!

Something got broken after node.js 8 update, please see these bug reports:

https://github.com/electron/electron/issues/8653
https://github.com/electron/electron-api-demos/issues/288
https://github.com/zeit/hyper/issues/1893
https://github.com/electron/electron/issues/9595

Or google for `Error: Generated checksum for did not match expected checksum.`.

I'm too lazy to get a stable reproduction case without other deps, but it can be fixed if you replace `'binary'` with `null` here:
https://github.com/malept/sumchecker/blob/master/index.js#L71

**Comment by addaleax** [comment]
I think this has been fixed by #5, can you try a latest version of this module?

**Comment by antelle** [comment]
Thanks, confirmed, new version of `sumchecker` doesn't have this issue 👍 
Sorry for that, it looks like old versions are still used in some packages.
