### ISSUE TITLE
CHECKSUM_LINE doesn't parse lines using multiple spaces correctly

### ISSUE THREAD

**Issue by craxal** [malept/sumchecker#8]
The CHECKSUM_LINE regex is currently `/^([\da-fA-F]+) ([ *])(.+)$/`, which expects only a single space to separate the hash from the filename. For most scenarios, this works fine.

In situations where a custom checksum file must be generated (such as custom builds based on forks of publicly available packages), this may break down. In my case, I was trying to use a checksum file meant for a custom Electron package wherein *two* spaces were being used to separate the hash from the filename. This, of course, broke my usage of `electron-packager`, which indirectly depends on `sumchecker`.

The CHECKSUM_LINE regex should be updated to something like `/^([\da-fA-F]+)\s+([ *])(.+)$/`.

**Comment by malept** [comment]
I'm following the format generated by utilities such as [`sha1sum`](https://en.wikipedia.org/wiki/Sha1sum#Examples) and [`md5sum`](https://en.wikipedia.org/wiki/Md5sum#File_produced).

How is your checksum file generated?

**Comment by craxal** [comment]
Unfortunately, I don't know. I'm not involved with the private builds. I have reached out to the folks who are to let them know about this issue. I suspect they might be using a small PowerShell script that needs tweeking.

I wasn't sure if there was a specific format that was being followed, but now I know. Thanks!
